---
# these override the official chart's values
# https://github.com/helm/charts/tree/master/stable/traefik#configuration
debug.enabled: false
replicas: 1
memoryRequest: 200Mi
memoryLimit: 200Mi
rbac:
  enabled: true
imageTag: "1.7"
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "*"
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
accessLogs:
  enabled: false
  # format: json
acme:
  enabled: true
  dnsProvider:
    name: cloudflare
    # cloudflare:
    #   CF_API_EMAIL:
    #   CF_API_KEY:
  email: aa23@protonmail.com
  staging: false
  logging: true
  onHostRule: true
  challengeType: dns-01
  # not needed if using k/v store
  persistence:
    enabled: false
    size: 1Gi
dashboard:
  serviceType: ClusterIP
  service:
    annotations:
      traefik.ingress.kubernetes.io/affinity: "true"
  statistics:
    recentErrors: 50
  enabled: true
  domain: chip-tf.adatechnologists.com
  auth:
    basic:
      # echo $(htpasswd -nb <AUTH-USER> <AUTH-PASS>)
      chipper: "$apr1$vonfQET/$fDaB7uYLgWReAELKfTWi81"
ssl:
  enabled: true
  enforced: true
  tlsMinVersion: "1.2"
  # ssllabs.com likes these as of end of 2018
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
# consul info here
# https://docs.traefik.io/configuration/backends/consul/
kvprovider:
  storeAcme: true
  importAcme: false
  consul:
    endpoint: "consul:8500"
    watch: true
    prefix: traefik
nodeSelector:
  chipper_frontend: "true"
gzip.enabled: false
