# Default values for wazuh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api:
  service:
    type: LoadBalancer
cluster:
  service:
    type: ClusterIP

  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "*"
  #   service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

image:
  repository: "wazuh/wazuh"
  tag: "3.8.2_6.5.4"
  pullPolicy: "IfNotPresent"

nameOverride: ""
fullnameOverride: ""

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/auth-remove-header: "true"
    traefik.ingress.kubernetes.io/auth-secret: kibana-basic-auth
    traefik.ingress.kubernetes.io/auth-type: basic
  enabled: false
  hosts:
    - chip-wz.adatechnologists.com
  paths: ["/"]
  tls: []

resources:
  limits:
   memory: "500Mi"
  requests:
   memory: "500Mi"

# nodeSelector:
#   chipper_static: "true"

tolerations: []

affinity: {}

persistence:
  name: data
  size: 10Gi
  accessModes:
    - ReadWriteOnce
