apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-cluster
  labels:
    app.kubernetes.io/name: {{ include "wazuh.name" . }}
    helm.sh/chart: {{ include "wazuh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  # TODO if/then for headless
  type: {{ .Values.cluster.service.type }}
  clusterIP: "None"
  ports:
    - name: wazuh-cluster
      targetPort: wazuh-cluster
      port: 1516
  selector:
    app.kubernetes.io/name: {{ include "wazuh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
