apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wazuh.name" . }}
    helm.sh/chart: {{ include "wazuh.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: {{ .Values.api.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: 55000
      targetPort: wazuh-api
      name: wazuh-api
    - port: 1514
      name: agent-events
      containerPort: agent-events
    - port: 1515
      targetPort: ossec-authd
      name: ossec-authd
  selector:
    app.kubernetes.io/name: {{ include "wazuh.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
