apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    helm.sh/chart: {{ include "fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fluentd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fluentd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # env:
          #   - name: "FLUENTD_SHARED_KEY"
          #     valueFrom:
          #       secretKeyRef:
          #         key: "sharedKey"
          #         name: {{ .Release.Name }}-sharedkey
          ports:
            - name: tcp
              containerPort: 24224
              protocol: TCP
            - name: beats
              containerPort: 5044
              protocol: TCP
          volumeMounts:
            - name: secrets
              mountPath: "/fluentd/etc/"
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "fluentd.fullname" . }}-secrets
            items:
              - key: fluent.conf
                path: fluent.conf
              - key: fluent.crt
                path: fluent.crt
              - key: fluent.key
                path: fluent.key
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
