apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "fluentd.fullname" . }}-secrets
  labels:
    app: {{ template "fluentd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent.conf: {{ .Files.Get "fluent.conf" | b64enc }}
  fluent.crt: {{ .Files.Get "tls/fluentd-server.pem" | b64enc }}
  fluent.key: {{ .Files.Get "tls/fluentd-server-key.pem" | b64enc }}
