filebeat:
 registry_file: /var/ossec/data/filebeat-registry
 clean_removed: true
 prospectors:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"
    document_type: json
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true
output:
 logstash:
   hosts: ["fluentd-int:5044"]
