---
apiVersion: apm.k8s.elastic.co/v1alpha1
kind: ApmServer
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: hotrock
spec:
  version: "7.1.1"
  nodeCount: 1
  output:
    elasticsearch:
      ref:
        name: hotrock
