{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-config
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit.conf: |-
{{ .Values.rawConfig | indent 4 }}

  fluent-bit-service.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    debug
        #Parsers_File parsers.conf
{{- if .Values.parsers.enabled }}
        Parsers_File parsers_custom.conf
{{- end }}
{{- if .Values.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
{{- end }}

  fluent-bit-input.conf: |-
    [INPUT]
        Name        forward
        Listen      0.0.0.0
        Port        24224
        Shared_Key  qu1nqHdHM7j1NV6kqgjSccxrsJGnVX4NOfg5bYBv4wjmn9edKVPdLpF40PK4SjcV
        tls         on
        tls.verify  off
        tls.debug   4

  fluent-bit-output.conf: |-
    [OUTPUT]
        Name   stdout
        Match  *
    [OUTPUT]
        Name  es
        Match *
        Host  {{ .Values.backend.es.host }}
        Port  {{ .Values.backend.es.port }}
        Logstash_Format On
        Retry_Limit False
        Type  {{ .Values.backend.es.type }}
{{- if .Values.backend.es.time_key }}
        Time_Key {{ .Values.backend.es.time_key }}
{{- end }}
{{- if .Values.backend.es.replace_dots }}
        Replace_Dots {{ .Values.backend.es.replace_dots }}
{{- end }}
{{- if .Values.backend.es.logstash_prefix }}
        Logstash_Prefix {{ .Values.backend.es.logstash_prefix }}
{{ else if .Values.backend.es.index }}
        Index {{ .Values.backend.es.index }}
{{- end }}
{{- if .Values.backend.es.http_user }}
        HTTP_User {{ .Values.backend.es.http_user }}
        HTTP_Passwd {{ .Values.backend.es.http_passwd }}
{{- end }}
{{if eq .Values.backend.es.tls "on" }}
        tls {{ .Values.backend.es.tls }}
        tls.verify {{ .Values.backend.es.tls_verify }}
        tls.debug {{ .Values.backend.es.tls_debug }}
{{- if .Values.backend.es.tls_ca }}
        tls.ca_file /secure/es-tls-ca.crt
{{- end }}
{{- end }}

  parsers.conf: |-
{{- if .Values.parsers.regex }}
{{- range .Values.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.json }}
{{- range .Values.parsers.json }}
    [PARSER]
        Name        {{ .name }}
        Format      json
{{- if .timeKeep }}
        Time_Keep   {{ .timeKeep }}
{{- end }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .decodeFieldAs  }}
        Decode_Field_As {{ .decodeFieldAs }} {{ .decodeField | default "log" }}
{{- end}}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}

{{- end -}}
