apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluent-bit.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fluent-bit.name" . }}
    helm.sh/chart: {{ include "fluent-bit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fluent-bit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fluent-bit.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 24224
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-service.conf
              subPath: fluent-bit-service.conf
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-input.conf
              subPath: fluent-bit-input.conf
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-filter.conf
              subPath: fluent-bit-filter.conf
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/fluent-bit-output.conf
              subPath: fluent-bit-output.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{- else }}{{ template "fluent-bit.fullname" . }}-config{{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: tcp
          readinessProbe:
            httpGet:
              path: /
              port: tcp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
