{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "mcas-siemagent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mcas-siemagent.name" . }}
    helm.sh/chart: {{ include "mcas-siemagent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "mcas-siemagent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "mcas-siemagent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
