apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcas-siemagent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mcas-siemagent.name" . }}
    helm.sh/chart: {{ include "mcas-siemagent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mcas-siemagent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mcas-siemagent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "mcas-siemagent.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["java"]
          args: ["-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Xms256m", "-Xmx256m", "-jar", "/mcas-siemagent-0.111.126-signed.jar", "--token", "$(MCAS_SIEMAGENT_TOKEN)"]
          env:
            - name: MCAS_SIEMAGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: MCAS_SIEMAGENT_TOKEN
                  name: {{ .Values.agent.token_secret_name | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
